### ISSUE TITLE
Account Creation

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/my.newspring.cc#33]
Accounts are not creating now:

~~~
Exception while invoking method 'createUser' Error: Name is required
~~~

Something [in here](https://github.com/NewSpring/apollos-core/blob/master/_source/lib/apollos.coffee) I assume

**Comment by jbaxleyiii** [comment]
Full log of issue:

```
[alpha.newspring.io] Exception while invoking method 'createUser' Error: Name is required
    at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
    at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
    at [object Object].Mongo.Collection.(anonymous function) [as upsert] (packages/aldeed:collection2/collection2.js:154:1)
    at Apollos.user.create.Accounts.createUser.email (packages/newspring:apollos-core/lib/lib/apollos.js:104:1)
    at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:999:1)
    at createUser (packages/accounts-password/password_server.js:718:1)
    at packages/accounts-password/password_server.js:738:1
    at tryLoginMethod (packages/accounts-base/accounts_server.js:161:1)
    at Object.Accounts._loginMethod (packages/accounts-base/accounts_server.js:277:1)
    at [object Object].Meteor.methods.createUser (packages/accounts-password/password_server.js:724:1)
Sanitized and reported to the client as: Name is required [400]
```

**Comment by jbaxleyiii** [comment]
fixed and closed with https://github.com/NewSpring/apollos-core/pull/64
